version: "3"

services:
  soapserver:
    build:
      context: ../..
      dockerfile: $PWD/Dockerfile
      args:
        JAR_FILE: './build/libs/*.jar'
    ports:
      - 8080:8080

networks:
  default:
    name: rest-ws
